url: "https://amgcube.com"
baseurl: ""

# Site settings
title: AMGCube
email: contact@amgcube.com
description: "AMGCube - Limited Space, Infinite Creativity."

# Team names, titles and social links
people:
- name: Leon Liu
  pic: 1
  position: Founder, PM
  
- name: Bo Liu
  pic: 2
  position: Co-Founder, CTO
  
- name: Jason Wang
  pic: 3
  position: Co-Founder, CCO
  

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/amgcube
  

# Postal address (optional, remove if not needed)
address:
  - line: 9 Falcon Ave, Thornlands
  - line: Brisbane, QLD 4164

# Build settings
markdown: kramdown
permalink: pretty

# Additional configurations
wdm:
  force_polling: false
logger: true
timezone: Australia/Brisbane
cache: true

# add 增加pages目录
include:
  - _pages
  
# 控制页面的URL
permalink: pretty

# 调整post文章
collections:
  posts:
    output: true
    permalink: /:path/
