url: "https://amgcube.com"
baseurl: ""

# Site settings
title: AMGCube
email: contact@amgcube.com
description: "AMGCube - Limited Space, Infinite Creativity."

# Team names, titles and social links
people:
- name: Leon Liu
  pic: 1
  position: Chief Marketing Officer
  social:
    - title: twitter
      url: https://twitter.com/
    - title: linkedin
      url: https://linkedin.com/

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/amgcube
  - title: github
    url: https://github.com/amgcube

# Postal address (optional, remove if not needed)
address:
  - line: 9 Falcon Ave, Thornlands
  - line: Brisbane, QLD 4164

# Build settings
markdown: kramdown
permalink: pretty
